import { Member } from "@src/types";

export const members: Member[] = [
  {
    id: "L1nKGr",
    name: "L1nKGr",
    role: "Researcher",
    bio: "深呼吸的时候，就能保持沉稳",
    avatarSrc: "/avatars/l1nkGr.png",
    sources: ["https://blog.000k.de/rss"],
  },
  {
    id: "Cyber_Kaiyo",
    name: "Cyber_Kaiyo",
    role: "Cyber_Kaiyo",
    bio: "ciallo～(∠・ω＜ )⌒ ☆",
    avatarSrc: "/avatars/Cyber_Kaiyo.jpg",
    sources: ["https://feed.cnblogs.com/blog/u/829717/rss"],
  },
  {
    id: "1c3W1ndy",
    name: "1c3W1ndy",
    role: "Researcher",
    bio: "全都不会打。",
    avatarSrc: "/avatars/1c3W1ndy.gif",
    sources: ["https://www.icewindy.cn/rss2.xml"],
  },
  {
    id: "QiSama",
    name: "QiSama",
    role: "Researcher",
    bio: "大佬们求带",
    avatarSrc: "/avatars/QiSama.jpg",
    sources: ["https://feed.cnblogs.com/blog/u/840519/rss"],
  },
  {
    id: "cyi",
    name: "cyi",
    role: "V&N联合战队成员、WwW_D4T4战队队长",
    bio: "不以物喜，不以己悲",
    avatarSrc: "/avatars/cyi.png",
    sources: ["https://feed.cnblogs.com/blog/u/795763/rss"],
  },
  {
    id: "HUPPE",
    name: "HUPP",
    role: "Researcher",
    bio: "深呼吸的时候，就能保持沉稳",
    avatarSrc: "/avatars/HUPPE.jpg",
    sources: ["https://huppee.github.io/huppe.github.io/feed.xml"],
  },
  {
    id: "E7h258",
    name: "E7h258",
    role: "Researcher",
    bio: "%df%5c Musc爱好者",
    avatarSrc: "/avatars/E7h258.jpg",
    sources: ["https://feed.cnblogs.com/blog/u/797904/rss"],
  },
];
