name: Trigger Vercel Build
on:
  schedule:
    - cron: '0 17 */2 * *'  # 每两天 UTC 时间 17:00 (北京时间次日 1:00)
  workflow_dispatch:  # 手动触发
jobs:
  build:
    name: Request Vercel Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        env:
          VERCEL_BUILD_HOOK: ${{ secrets.VERCEL_BUILD_HOOK }}
        run: curl -X POST $VERCEL_BUILD_HOOK
