name: Trigger Vercel Build
on:
  schedule:
    - cron: '0 1 */2 * *' # At 00:05 on 星期二.
  workflow_dispatch:  # 手动触发
jobs:
  build:
    name: Request Vercel Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        env:
          VERCEL_BUILD_HOOK: ${{ secrets.VERCEL_BUILD_HOOK }}
        run: curl -X POST $VERCEL_BUILD_HOOK
