name: Trigger Vercel Build

on:
  schedule:
    - cron: '0 17 */2 * *'  # 每两天 UTC 时间 17:00 (北京时间次日 1:00)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build
        run: curl -s -X POST ${{ secrets.VERCEL_BUILD_HOOK }}
