name: Trigger Vercel Build
on:
  schedule:
    - cron: '0 1 */2 * *' #每两天后的一点.
  workflow_dispatch:  # 手动触发
jobs:
  build:
    name: Request Vercel Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        env:
          VERCEL_BUILD_HOOK: ${{ secrets.VERCEL_BUILD_HOOK }}
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_YrgZ0B2rSRIYGBP2MosnrnRgB55b/POM8ngkn5x
